FROM nginx:mainline-alpine

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy already-built MkDocs site from local folder
COPY ./site /usr/share/nginx/html


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

#Maintance Note: Testing was done on alpine:3.22